geometry_msgs/Pose2D[] red_small
geometry_msgs/Pose2D[] red_large
geometry_msgs/Pose2D[] blue_small
geometry_msgs/Pose2D[] blue_large
geometry_msgs/Pose2D[] yelow_small
geometry_msgs/Pose2D[] yelow_large

geometry_msgs/Point[] red_small_3d
geometry_msgs/Point[] red_large_3d
geometry_msgs/Point[] blue_small_3d
geometry_msgs/Point[] blue_large_3d
geometry_msgs/Point[] yelow_small_3d
geometry_msgs/Point[] yelow_large_3d
